Add amplified orders
mangrovedao/subgraph pull request #34
Opened 2024-02-16 09:01 UTC by DanielRX

2024-02-16 10:11 UTC, Louis-Amas requested changes

2024-02-16 10:11 UTC, Louis-Amas commented on .prettierrc
> +  "printWidth": 160
A bit, too wide 120 will be perfect :)

2024-02-16 10:11 UTC, Louis-Amas commented on src/mangrove-amplifier.ts
> +  // offer.save();
Why no save here ?

2024-02-16 10:16 UTC, Louis-Amas submitted a review, later dismissed

2024-02-19 09:58 UTC, Louis-Amas commented on src/mangrove-amplifier.ts
> +  log.error("Adding offer to bundle: {}", [bundle.id]);
Remove the debugging statement :)

2024-02-22 14:24 UTC, maxencerb approved these changes

2024-02-22 14:31 UTC, maxencerb submitted a review, later dismissed

2024-02-22 14:33 UTC, maxencerb submitted a review, later dismissed

2024-02-22 14:38 UTC, maxencerb approved these changes

2024-02-22 14:38 UTC, merged